name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Infomaniak
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: jo504.ftp.infomaniak.com
          username: jo504_ncd
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/sites/InfraGuard.swissnexo.ch

            # Vérifie si repo existe
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/baha-eddine-ammar/pfe_test1.git .
            else
              echo "Updating repository..."
              git reset --hard
              git clean -fd
              git pull origin main
            fi

            # Installer dépendances
            composer install --no-dev --optimize-autoloader

            # Migrations (ignore erreur si pas de droits)
            php artisan migrate --force || true

            # Cache Laravel
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
